version: "3.9"
services:

  server:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: "postgres"

    depends_on:
      - postgres


  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "amcef"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"









